# Generated by Django 4.2.4 on 2023-12-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Money_recieved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Money_sent',
        ),
    ]
