# Generated by Django 4.2.4 on 2023-12-08 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.TextField(max_length=30)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('usernames', models.ManyToManyField(to='polls.username')),
            ],
        ),
    ]
