# Generated by Django 4.2.4 on 2023-12-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_rename_usernames_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.group'),
        ),
    ]
