# Generated by Django 4.2.4 on 2023-12-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_user_money_recieved_remove_user_money_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money_recieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='money_sent',
            field=models.IntegerField(default=0),
        ),
    ]
