# Generated by Django 4.2.4 on 2023-12-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_user_money_recieved_user_money_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
