# Generated by Django 4.2.4 on 2023-12-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_delete_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='no_of_users',
            field=models.IntegerField(default=2),
        ),
    ]
